# -*- coding: utf-8 -*-
"""Rent calculator .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qw_1qTczrI86SJTQ5l-E11UDP9gbVAjw
"""

## Inputs we need from the user
# total rent
# total food ordered for snacking
# electricity units spend
# charge per unit
# persons living in room

## Output
# Total amount you've to pay is

rent = int(input("Enter your room rent = "))
food = int(input ("Enter the amount of food ordered = "))
electricity_spend = int(input ("Enter the total of electricity spend = "))
charge_per_unit = int(input (" Enter the charge per unit ="))
persons = int(input ("Enter the number of persons living in room = "))
total_bill = electricity_spend * charge_per_unit

Output = (food + rent + total_bill) // persons

print("Each person will pay = " , Output)